#тип хранилища данных (memory/sqlite/postgres)
storage_type: postgres

#конфигурация http сервера
http_port: ":8080"

#тип интерфейса (cli/rest_api)
interface: rest_api

#конфигурация postgres
postgres:
  host: "db"
  port: 5432
  user: "postgres"
  password: "qwerty"
  dbname: "postgres"
  sslmode: "disable"