# тип хранилища данных (memory/sqlite/postgres)
storage_type: memory

# конфигурация handler
host_addr: "localhost:8080"

# конфигурация http сервера
http_port: ":8080"

# конфигурация grpc сервера
grpc_port: ":8081"

# тип интерфейса (cli/rest_api/grpc)
interface: grpc

# конфигурация postgres
postgres:
  host: "db"
  port: 5432
  user: "postgres"
  password: "qwerty"
  dbname: "postgres"
  sslmode: "disable"